package satellite

import (
	"context"
	"encoding/binary"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"time"

	esphome "github.com/ygelfand/go-esphome-device"

	"github.com/ygelfand/echolocal/internal/alog"
	"github.com/ygelfand/echolocal/internal/speaker"
)

// announceFormat is what Home Assistant is asked to convert announcements and media to. It runs
// the conversion through ffmpeg, so asking for plain WAV at the pipeline's rate means no decoder
// here: strip the header and the rest is samples.
var announceFormat = []esphome.MediaFormat{
	{Format: "wav", SampleRate: speaker.VoiceRate, Channels: 1, SampleBytes: 2},
	{Format: "wav", SampleRate: speaker.VoiceRate, Channels: 1, SampleBytes: 2, Announcement: true},
}

const fetchTimeout = 30 * time.Second

// announce plays what Home Assistant asks for, then reports back. It runs off the connection's
// read loop: fetching and playing must not block it.
func (t *conversation) announce(a esphome.Announce) {
	slog.Info("announce", "text", a.Text, "start_conversation", a.StartConversation)

	// One claim covers both urls, so silencing an announcement stops the whole thing rather than
	// letting the second one start once the first has been drained.
	claim := t.sound.Claim("announce", func(ctx context.Context, _ *speaker.Player) error {
		t.player.mp.SetState(esphome.MediaPlayerAnnouncing)
		defer t.player.mp.SetState(esphome.MediaPlayerIdle)

		for _, url := range []string{a.PreannounceMediaID, a.MediaID} {
			if url == "" {
				continue
			}
			if err := t.play(ctx, url); err != nil {
				return err
			}
		}
		return nil
	})

	go alog.Safely("announce", func() {
		<-claim.Done()

		if err := claim.Err(); err != nil {
			slog.Error("playing the announcement failed", "err", err)
		}
		if err := t.vs.AnnounceFinished(claim.Err() == nil && !claim.Stopped()); err != nil {
			slog.Error("reporting the announcement failed", "err", err)
		}

		// Home Assistant uses this to open a conversation without a wake word. An announcement that
		// was cut off was cut off on purpose, so nothing follows it.
		if a.StartConversation && !claim.Stopped() {
			t.Start(0)
		}
	})
}

// play fetches audio and queues it. Home Assistant serves it converted to announceFormat. Waiting
// for it to be heard is the driver's, not ours: this returns as soon as it has been handed over.
func (t *conversation) play(ctx context.Context, url string) error {
	samples, err := fetch(ctx, url)
	if err != nil {
		return err
	}
	slog.Info("playing announcement", "samples", len(samples))

	t.post(event{kind: evPlaying})
	t.speaker.PlayVoice(samples)

	// Speech generated by a text to speech engine stops on its last sound with no silence after it,
	// and the interpolating resampler needs a few samples beyond the end to run out. Without a tail
	// the final word sounds cut off.
	t.speaker.PlayVoice(make([]int16, speaker.VoiceRate*replyTail/1000))
	return nil
}

// fetch downloads audio Home Assistant is serving and decodes it. The request carries the context, so
// silencing a sound abandons the download rather than leaving it to arrive and be thrown away.
func fetch(ctx context.Context, url string) ([]int16, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}

	client := &http.Client{Timeout: fetchTimeout}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: %s", url, resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return monoPCM(body)
}

// replyTail is the silence added after speech, in milliseconds.
const replyTail = 250

// monoPCM takes 16-bit samples out of a RIFF/WAVE body, walking the chunks rather than assuming a
// 44-byte header: a converted file can carry extra chunks before the data.
//
// Sizes are handled as uint64. A 32-bit int cannot hold a large RIFF size, and a chunk claiming
// one turns negative, which slips past a bounds check and panics on the slice.
func monoPCM(body []byte) ([]int16, error) {
	if len(body) < 12 || string(body[0:4]) != "RIFF" || string(body[8:12]) != "WAVE" {
		return nil, fmt.Errorf("not a WAVE file: %d bytes", len(body))
	}

	total := uint64(len(body))
	for off := uint64(12); off+8 <= total; {
		id := string(body[off : off+4])
		size := uint64(binary.LittleEndian.Uint32(body[off+4 : off+8]))
		off += 8

		end := off + size
		if end > total {
			end = total
		}

		if id == "data" {
			pcm := body[off:end]
			samples := make([]int16, len(pcm)/2)
			for i := range samples {
				samples[i] = int16(binary.LittleEndian.Uint16(pcm[i*2:]))
			}
			return samples, nil
		}

		off = end
		if size%2 == 1 {
			off++
		}
	}
	return nil, fmt.Errorf("no data chunk in %d bytes", total)
}
