package satellite

import (
	"encoding/binary"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"time"

	esphome "github.com/ygelfand/go-esphome-device"

	"github.com/ygelfand/echolocal/internal/alog"
	"github.com/ygelfand/echolocal/internal/speaker"
)

// announceFormat is what Home Assistant is asked to convert announcements and media to. It runs
// the conversion through ffmpeg, so asking for plain WAV at the pipeline's rate means no decoder
// here: strip the header and the rest is samples.
var announceFormat = []esphome.MediaFormat{
	{Format: "wav", SampleRate: speaker.VoiceRate, Channels: 1, SampleBytes: 2},
	{Format: "wav", SampleRate: speaker.VoiceRate, Channels: 1, SampleBytes: 2, Announcement: true},
}

const fetchTimeout = 30 * time.Second

// announce plays what Home Assistant asks for, then reports back. It runs off the connection's
// read loop: fetching and playing must not block it.
func (t *voiceTurn) announce(a esphome.Announce) {
	slog.Info("announce", "text", a.Text, "start_conversation", a.StartConversation)

	go alog.Safely("announce", func() {
		ok := true
		t.player.mp.SetState(esphome.MediaPlayerAnnouncing)

		for _, url := range []string{a.PreannounceMediaID, a.MediaID} {
			if url == "" {
				continue
			}
			if err := t.play(url); err != nil {
				slog.Error("playing the announcement failed", "err", err)
				ok = false
			}
		}

		t.player.mp.SetState(esphome.MediaPlayerIdle)
		if err := t.vs.AnnounceFinished(ok); err != nil {
			slog.Error("reporting the announcement failed", "err", err)
		}

		// Home Assistant uses this to open a conversation without a wake word.
		if a.StartConversation {
			t.Start("")
		}
	})
}

// play fetches audio and queues it. Home Assistant serves it converted to announceFormat.
func (t *voiceTurn) play(url string) error {
	if t.speaker == nil {
		return fmt.Errorf("no speaker")
	}

	client := &http.Client{Timeout: fetchTimeout}
	resp, err := client.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("%s: %s", url, resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	samples, err := monoPCM(body)
	if err != nil {
		return err
	}
	slog.Info("playing announcement", "bytes", len(body), "samples", len(samples))

	t.speaker.PlayVoice(samples)

	// Speech generated by a text to speech engine stops on its last sound with no silence after it,
	// and the interpolating resampler needs a few samples beyond the end to run out. Without a tail
	// the final word sounds cut off.
	t.speaker.PlayVoice(make([]int16, speaker.VoiceRate*replyTail/int(time.Second/time.Millisecond)))

	for t.speaker.Queued() > 0 {
		time.Sleep(50 * time.Millisecond)
	}
	// An empty queue only means the samples have reached the driver; the hardware buffer still has
	// what it has been given left to play.
	time.Sleep(hardwareTail)
	return nil
}

// replyTail is the silence added after speech, in milliseconds, and hardwareTail is how long the
// playback buffer holds once nothing more is queued.
const (
	replyTail    = 250
	hardwareTail = 150 * time.Millisecond
)

// monoPCM takes 16-bit samples out of a RIFF/WAVE body, walking the chunks rather than assuming a
// 44-byte header: a converted file can carry extra chunks before the data.
//
// Sizes are handled as uint64. A 32-bit int cannot hold a large RIFF size, and a chunk claiming
// one turns negative, which slips past a bounds check and panics on the slice.
func monoPCM(body []byte) ([]int16, error) {
	if len(body) < 12 || string(body[0:4]) != "RIFF" || string(body[8:12]) != "WAVE" {
		return nil, fmt.Errorf("not a WAVE file: %d bytes", len(body))
	}

	total := uint64(len(body))
	for off := uint64(12); off+8 <= total; {
		id := string(body[off : off+4])
		size := uint64(binary.LittleEndian.Uint32(body[off+4 : off+8]))
		off += 8

		end := off + size
		if end > total {
			end = total
		}

		if id == "data" {
			pcm := body[off:end]
			samples := make([]int16, len(pcm)/2)
			for i := range samples {
				samples[i] = int16(binary.LittleEndian.Uint16(pcm[i*2:]))
			}
			return samples, nil
		}

		off = end
		if size%2 == 1 {
			off++
		}
	}
	return nil, fmt.Errorf("no data chunk in %d bytes", total)
}
