// Command mkmanifest writes the manifest a device fetches to learn a release exists.
//
// It lives here rather than in the release workflow so that the file CI publishes and the struct echod
// parses are the same definition. A manifest generated by a shell script would be free to drift from
// what the device expects, and the failure would only show up as a device that will not update.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/ygelfand/echolocal/internal/update"
)

func main() {
	var (
		m    update.Manifest
		file = flag.String("file", "", "the binary this release ships, hashed and measured")
		out  = flag.String("out", "", "where to write the manifest, or stdout")
	)
	flag.StringVar(&m.Version, "version", "", "version as Home Assistant will compare it")
	flag.StringVar(&m.URL, "url", "", "where the binary can be fetched from")
	flag.StringVar(&m.Title, "title", "", "title for Home Assistant's update card")
	flag.StringVar(&m.Notes, "notes", "", "release notes, shown on the card")
	flag.StringVar(&m.ReleaseURL, "release-url", "", "what the card's link points at")
	flag.Parse()

	if err := run(m, *file, *out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(m update.Manifest, file, out string) error {
	if m.Version == "" || m.URL == "" || file == "" {
		return fmt.Errorf("mkmanifest: -version, -url and -file are all required")
	}

	f, err := os.Open(file)
	if err != nil {
		return err
	}
	defer f.Close()

	sum := sha256.New()
	size, err := io.Copy(sum, f)
	if err != nil {
		return err
	}
	m.Size, m.SHA256 = size, hex.EncodeToString(sum.Sum(nil))

	// The same rules the device applies, so a release cannot publish a manifest every device will reject.
	if err := m.Valid(); err != nil {
		return err
	}

	encoded, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	encoded = append(encoded, '\n')

	if out == "" {
		_, err = os.Stdout.Write(encoded)
		return err
	}
	return os.WriteFile(out, encoded, 0o644)
}
