package media

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"time"

	esphome "github.com/ygelfand/go-esphome-device"

	"github.com/ygelfand/echolocal/internal/hardware/speaker"
)

// Formats is what Home Assistant is asked to convert to. It runs the conversion through ffmpeg, so
// asking for plain WAV means the converted track needs no decoding here: strip the header and the
// rest is samples. The announce path still decodes whatever the TTS engine hands over (see decode),
// because Home Assistant serves that in the engine's own container rather than converting it.
//
// Music gets the codec's own rate and both channels, so nothing is resampled and nothing is thrown
// away. Announcements stay at the pipeline's rate: they are one voice, and the bandwidth would buy
// nothing but a longer wait before the device says anything.
var Formats = []esphome.MediaFormat{
	{Format: "wav", SampleRate: speaker.Rate, Channels: speaker.Channels, SampleBytes: 2},
	{Format: "wav", SampleRate: speaker.VoiceRate, Channels: 1, SampleBytes: 2, Announcement: true},
}

// Tail is the silence added after speech, in milliseconds. Speech generated by a text to speech
// engine stops on its last sound with no silence after it, and the interpolating resampler needs a
// few samples beyond the end to run out. Without a tail the final word sounds cut off.
const Tail = 250

const fetchTimeout = 30 * time.Second

// Fetch downloads audio Home Assistant is serving and decodes it. The request carries the context, so
// silencing a sound abandons the download rather than leaving it to arrive and be thrown away.
func Fetch(ctx context.Context, url string) ([]int16, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}

	client := &http.Client{Timeout: fetchTimeout}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: %s", url, resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return decode(body)
}
